// <auto-generated />
using System;
using Infrastructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GarageContext))]
    [Migration("20250322120801_EditedCarModel")]
    partial class EditedCarModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.AppRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("RolesTable");
                });

            modelBuilder.Entity("Domain.Models.AppUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verificated")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("UsersTable");
                });

            modelBuilder.Entity("Domain.Models.Car", b =>
                {
                    b.Property<Guid>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CarBrand")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CarBrand");

                    b.Property<string>("CarOwnerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CarOwnerName");

                    b.Property<string>("CarOwnerPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CarOwnerPhone");

                    b.Property<string>("CarQRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarSpz")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CarSpz");

                    b.Property<string>("CarVIN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CarVIN");

                    b.Property<string>("DefaultOwnerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CarId");

                    b.HasIndex("OwnerId");

                    b.ToTable("CarsTable", (string)null);
                });

            modelBuilder.Entity("Domain.Models.EditUsertToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TokenUsed")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Token");

                    b.ToTable("EditUserTokenTable");
                });

            modelBuilder.Entity("Domain.Models.ImageRepair", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ForRepairId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("ForRepairId");

                    b.ToTable("ImagesTable");
                });

            modelBuilder.Entity("Domain.Models.Repair", b =>
                {
                    b.Property<Guid>("RepairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CarSpz")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CarSpz");

                    b.Property<DateOnly?>("DateofRepair")
                        .HasColumnType("date")
                        .HasColumnName("DateofRepair");

                    b.Property<string>("Kilometres")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Kilometres");

                    b.Property<bool>("OilServis")
                        .HasColumnType("bit")
                        .HasColumnName("OilServis");

                    b.Property<string>("RepairDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RepairDesc");

                    b.Property<Guid?>("RepairForCarId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RepairForCarId");

                    b.Property<int?>("RepairPrice")
                        .HasColumnType("int")
                        .HasColumnName("RepairPrice");

                    b.HasKey("RepairId");

                    b.HasIndex("RepairForCarId");

                    b.ToTable("RepairsTable", (string)null);
                });

            modelBuilder.Entity("Domain.Models.UserRefreshTokens", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Expires")
                        .HasColumnType("date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenForUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshTokenId");

                    b.ToTable("TokensTable");
                });

            modelBuilder.Entity("Domain.Models.UserRole", b =>
                {
                    b.Property<string>("UsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("RoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsId", "RoId");

                    b.HasIndex("RoId");

                    b.ToTable("UserRoleTable");
                });

            modelBuilder.Entity("Domain.Models.Car", b =>
                {
                    b.HasOne("Domain.Models.AppUser", "Owner")
                        .WithMany("CarsOwnedByUser")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Models.ImageRepair", b =>
                {
                    b.HasOne("Domain.Models.Repair", "ForRepair")
                        .WithMany("ImagesForThisRepair")
                        .HasForeignKey("ForRepairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForRepair");
                });

            modelBuilder.Entity("Domain.Models.Repair", b =>
                {
                    b.HasOne("Domain.Models.Car", "RepairForCar")
                        .WithMany("CarRepairs")
                        .HasForeignKey("RepairForCarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RepairForCar");
                });

            modelBuilder.Entity("Domain.Models.UserRole", b =>
                {
                    b.HasOne("Domain.Models.AppRole", "Ro")
                        .WithMany("UsersInThisRole")
                        .HasForeignKey("RoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.AppUser", "Us")
                        .WithMany("RolesOfUser")
                        .HasForeignKey("UsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ro");

                    b.Navigation("Us");
                });

            modelBuilder.Entity("Domain.Models.AppRole", b =>
                {
                    b.Navigation("UsersInThisRole");
                });

            modelBuilder.Entity("Domain.Models.AppUser", b =>
                {
                    b.Navigation("CarsOwnedByUser");

                    b.Navigation("RolesOfUser");
                });

            modelBuilder.Entity("Domain.Models.Car", b =>
                {
                    b.Navigation("CarRepairs");
                });

            modelBuilder.Entity("Domain.Models.Repair", b =>
                {
                    b.Navigation("ImagesForThisRepair");
                });
#pragma warning restore 612, 618
        }
    }
}
